version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: docker

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080


  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: mongo
    #  MONGO_INITDB_ROOT_PASSWORD: docker

  #mongo-express:
  #  image: mongo-express
  #  restart: always
  #  ports:
  #    - 8081:8081
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: docker
